Add copyright, fix exits

diff --git a/ilmbase.SlackBuild b/ilmbase.SlackBuild
--- a/ilmbase.SlackBuild
+++ b/ilmbase.SlackBuild
@@ -1,11 +1,26 @@
 #!/bin/sh
 #
-# SlackBuild for IlmBase
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
-# Visit SlackPack at http://sotirov-bg.net/slackpack/
+# Slackware build script for IlmBase
+# Copyright (C) 2007,2010,2012 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+# 
+# $Id: ilmbase.SlackBuild,v 1.3 2012/09/02 08:15:12 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=ilmbase
 VERSION=1.0.2
@@ -33,12 +48,12 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 3
 cd $SRC
 fix_source
 
 # Apply patches
-patch -p1 -b -z.orig < $CWD/$NAME-$VERSION.diff
+patch -p1 -b -z.orig < $CWD/$NAME-$VERSION.diff || exit 4
 
 # Configure
 CFLAGS=$SLKCFLAGS \
@@ -50,11 +65,11 @@ CXXFLAGS=$SLKCFLAGS \
             --mandir=/usr/man \
             --enable-shared=yes \
             --enable-static=no \
-            --enable-threading
+            --enable-threading || exit 5
 
 # Build & install
-make all || exit 1 
-make DESTDIR=$PKG install
+make all || exit 6
+make DESTDIR=$PKG install || exit 7
 
 # Prepare
 ( cd $PKG; strip_lib )
@@ -71,6 +86,7 @@ install -m 644 $CWD/slack-required      $SBDIR/slack-required
 install -m 644 $CWD/$NAME-$VERSION.diff $SBDIR/$NAME-$VERSION.diff
 install -m 644 $CWD/$NAME.SlackBuild    $SBDIR/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -78,6 +94,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optional)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
